### ISSUE TITLE
Report broken filename(s)

### ISSUE THREAD

**Issue by wkollernhm** [gbhl/bhl-europe#383]
If filenames aren't according to the FSG, the tool detects it and outputs the error message "Error: Filename convention broken! rename your page files according to File Submission Guidelines (FSG).". The name of the actual file must be added to the message so that naming can fixed - else there is no feedback to the user.

@chris-sleep 
@lobajuluwa 
@heimor

**Comment by mindcatch-com** [comment]
i added the name of the first 10 files in order as example and added the nomenclatur info to the message

@heimor 
@wkollernhm

**Comment by wkollernhm** [comment]
Only the affected files should be reported. The first 10 files might be working but inbetween there might be some incorrect filenames. Change this to report only the broken filenames.

**Comment by mindcatch-com** [comment]
done.
but be aware that now each corrupt file is reported (may many)

**Comment by mindcatch-com** [comment]
additional update.
you will now see if structure requirements are not fulfilled much earlier in process when preparing step 2-4 (testing)

@wkollernhm 
@heimor

**Comment by mindcatch-com** [comment]
fixed. see git.

> Only the affected files should be reported. The first 10 files might be
> working but inbetween there might be some incorrect filenames. Change this
> to report only the broken filenames.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/bhle/bhle/issues/383#issuecomment-4537673

Mit freundlichen Grüßen,

Ing. Andreas Mehrrath, BSc, MSc

---

Senior Developer - Geschäftsführung

mindCatch(tm) software solutions

Kirchenfeldgasse 9
A-2202 Enzersfeld

Tel.: +43 (0)664 117 01 63
Fax.: +43 (0)1 817 4955 1958

mailto:mehrrath@mindcatch.com

http://www.mindcatch.com

---

**Comment by mindcatch-com** [comment]
fixed since 3+ days please test and close.

@wkollernhm
@heimor

**Comment by wkollernhm** [comment]
I've tried this with the example upload provided by uk-rbge (path: uk-rbge/VOC/VoC_0000_1911_0000/). It contains several invalid named files.

The invalid files are detected but the "Affected File" output is empty.

Example:

Error: Filename convention broken! Minimal requirements (PREFIX_SEQUENCE nomenclatur) not fulfilled.
            Please rename your uploaded page files according to the File Submission Guidelines.
            (FSG: PREFIX | SEQUENCE | [TYPE | PAGENUMBER])!
            Affected File: 0003.tif.tax

Error: Filename convention broken! Minimal requirements (PREFIX_SEQUENCE nomenclatur) not fulfilled.
            Please rename your uploaded page files according to the File Submission Guidelines.
            (FSG: PREFIX | SEQUENCE | [TYPE | PAGENUMBER])!
            Affected File:

**Comment by mindcatch-com** [comment]
hi wolfgang, please retest this, thanks.

@wkollernhm 

besides: can you undock the database update from jenkins main job
it costs much test time when the database is dropped each time 
and the layout is stable since last 3 weeks and therefore this dropping and
re-creating makes no sense but costs much time for us both.

**Comment by wkollernhm** [comment]
I will work something out for not re-creating the DB each time.

**Comment by wkollernhm** [comment]
This is still broken. I've re-tested it with uk-rbge/VOC/VoC_0000_1911_0000/ - now all affected file entries are  empty.

You can reproduce this error by logging into bhl-test as admin and run the final step on the content quoted above.

**Comment by mindcatch-com** [comment]
because every sequence is 1911 in this complete wrong example.
@wkollernhm

**Comment by mindcatch-com** [comment]
i have seen in namefixes you have corrected this, right? problem occurs there too?

**Comment by wkollernhm** [comment]
Identifying invalid file names should be possible with any files - of course since thats what the feature is all about.

Doesn't make sense for me to test the output of the warning with valid files only?

**Comment by mindcatch-com** [comment]
done. 
1 wrong file is notified per level as example and hints to others...

**Comment by wkollernhm** [comment]
as noted above, all invalid files should be reported to the user. Else the user will have to correct the files one by one and reload every time.
