### ISSUE TITLE
Final PI step failing for a monograph without pagetype/number data

### ISSUE THREAD

**Issue by chris-sleep** [gbhl/bhl-europe#390]
Running PI on es-csic/CSIC000324590 with latest PI on bhl-test: (monograph)
associated issue #329 

When I invoke the check/release media step via the PI tool, no response comes back: there's an immediate error thrown in /var/log/apache2/error_log:

PHP Fatal error:  Uncaught exception 'DOMException' with message 'Not Found Error' in /var/www/ingest/inc/inc/olef_mods.php:95\nStack trace:\n#0 /var/www/ingest/inc/inc/olef_mods.php(95): DOMNode->removeChild(Object(DOMElement))\n#1 /var/www/ingest/inc/get_mets.php(29): include_once('/var/www/ingest...')\n#2 /var/www/ingest/inc/step_kernel.php(34): include_once('/var/www/ingest...')\n#3 /var/www/ingest/index.php(92): include_once('/var/www/ingest...')\n#4 {main}\n  thrown in /var/www/ingest/inc/inc/olef_mods.php on line 95, referer: http://bhl-test.nhm.ac.uk/preingest/index.php?menu_nav=ingest_list

The monograph files are purely IDENTIFIER_SEQUENCE.tif format and the .aip/olef.xml has been updated with the path and taxon data

**Comment by wkollernhm** [comment]
Re-assigned to @mehrrath - please fix immediately.

**Comment by mindcatch-com** [comment]
i think i have fixed that problem in 1.70 

@chris-sleep

please set error level and display errors in php.ini higher/on, i think this would be appropriate for a test system ;o)

**Comment by chris-sleep** [comment]
error_reporting set to = E_ALL | E_STRICT but that doesn't show any more detail in the log; 

display_errors is off as the host is an integration test host rather than a general test host, and that will hit testing across a range of applications. I'm happy to identify a content chunk to try an ingest on directly for your development/test machine if that will help?

(note that the issue is still occuring on bhl-int (1.70 beta2)

**Comment by chris-sleep** [comment]
1.71 beta (serials 1.0) now generating .aip for monographs again;

**Comment by wkollernhm** [comment]
@chris-sleep any update on this issue? I do not want to close a bug opened by you, but this seems to work now.

**Comment by chris-sleep** [comment]
I've seen the test monograph go forward now, happy to confirm and close this bug, thanks.
